version: '2'

services:
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - "127.0.0.1:1234:1234"
    volumes:
      - ./docker/adminmongo/app.json:/app/user/config/app.json:ro

  app:
    build:
      context: .
    environment:
      - CONFIG_WEB_USERNAME=admin
      - CONFIG_WEB_PASSWORD=123456
      - DEBUG=pushserver:*
      - MONGO_URI=mongodb://mongo/pushserver
      - REDIS_URL=http://redis:6379
    depends_on:
      - mongo
      - redis
    ports:
      - "127.0.0.1:80:18080"

  mongo:
    image: mongo:4.2.2
    volumes:
      - .:/app:ro
      - ./docker/data/mongo:/data/db

  redis:
    image: redis:5.0.7-alpine
    command: redis-server --appendonly yes
    volumes:
      - .:/app:ro
      - ./docker/data/redis:/data
