name: Test
on: push
jobs:
  unit_test:
    name: Unit test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('npm-shrinkwrap.json') }}
          restore-keys: |
            npm-

      - run: npm ci
      - run: npm run lint
      - run: npm run coverage

      - name: Run coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.node }}
          parallel: true

      - name: Upload npm logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: npm-logs
          path: "~/.npm/_logs/**/*"

  finish:
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
    - name: Mark coveralls finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
